- hosts: workstation
  gather_facts: false
  tasks:
  #Get the groups that we need
  - name: OpenStack servers
    include_role:
      name: osp-facts

  # - name: Curl website
  #   command: curl http://{{ (groups['frontends'])[0] }}
  #   register: webpage
  - uri:
      url: http://{{ groups['frontends'][0] }}
      return_content: yes
    register: webpage
    loop: "{{ groups['frontends'] }}"

  - debug:
      var: webpage

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.results[0].content"
    tags:
      - osp.smoke