---
- hosts: workstation
  gather_facts: false
  tasks:

  - name: OpenStack servers
    os_server_info:
     cloud: openstack
     server: 'frontend'
    register: r_os_server_info
    
  - name: Curl website
    uri:
      url: "http://{{item.public_v4}}/ping"
      return_content: yes
    loop: '{{ groups.frontends }}'
    until: '"alive" in result.content'
    retries: 10
    delay: 1
    register: result
    delegate_to: localhost
    
  - debug:
      var: r_webpage.results[0].content

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in r_webpage.results[0].content"
    tags:
      - osp.smoke