- hosts: workstation
  gather_facts: false
  pre_tasks: 
  vars:
    - 
  tasks:
  - name: Get OpenStack Instances
    os_server_info:
      cloud: openstack
      server: frontend*
      filters:
        vm_state: active
    register: osp_frontends

  - name: Frontend HTTP Request
    uri:
      url: "http://{{ item.public_v4 }}"
      return_content: yes
      status_code: 200
    loop: "{{ osp_frontends.openstack_servers }}"
    register: webpage
    failed_when: "Ansible has done its job" not in webpage.content