---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    name: "{{ item.value.name }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    meta:
      group: "{{ item.value.meta.0.group }}" 
      deployment_name: "{{ item.value.meta.0.deployment_name }}" 
    flavor: "{{ item.value.flavor }}"
    security_groups: 
      - "{{ item.value.security_group }}"
    network: int_network
    #nics: undefined # not required. A list of networks to which the instance's interface should be attached. Networks may be referenced by net-id/net-name/port-id or port-name.,Also this accepts a string containing a list of (net/port)-(id/name) Eg: nics: "net-id=uuid-1,port-name=myport" Only one of network or nics should be supplied.
    #auth: "{{ os_auth }}"
    userdata: |
      #!/bin/bash
      mkdir -p /home/cloud-user/.ssh
      echo {{ openstack_key }} >>   /home/cloud-user/.ssh/authorized_keys
      chown -R cloud-user: /home/cloud-user/.ssh
      chmod u=rw,go= /home/cloud-user/.ssh/authorized_keys
      chmod u=rwx,go= /home/cloud-user/.ssh
  loop: "{{ osp_servers | dict2items }}"

- name: Add floating IP to Servers
  os_floating_ip:
    server: "{{ item.value.name }}"
    network: ext_network
    auth: "{{ os_auth }}"
  loop: "{{ osp_servers | dict2items }}"

- name: Wait for server to be available
  wait_for:
    timeout: 600
    port: 22