---
# Initial, common, system setup steps

- name: enable sudo without tty for some ansible commands
  replace:
    path: /etc/sudoers
    regexp: '^Defaults\s*requiretty'
    replace: 'Defaults  !requiretty'
    backup: yes

- name: pull repo file from local site into /etc
  become: yes
  become_user: root
  copy:
      dest: /etc/yum.repos.d/internal.repo
      src: original.repo
      mode: u=rw,g=r,o=r

